
file = open("glapi_table.h",'r')
file1 = open("call_mapping.hpp","w")
data= []
data.append("/*this file is generated by gen_call_table.py.\
	please do not modify it manaully.*/\n\
	#include<GL/glxext.h>\n#include\"function.h\"")
for line in file.readlines()[2:1332]:
	line1 = 'if(strcmp("gl%s",call_name)==0){' % (line[17:-3])
	line2 = '  PFNGL%sPROC func = (PFNGL%sPROC)glXGetProcAddress((const GLubyte*)"gl%s");'\
	% (line[17:][:-3].upper(),line[17:][:-3].upper(),line[17:-3])
	line3 = '  continue;\n}'
	disp = '%s\n%s\n%s' % (line1,line2,line3)
	data.append(disp)
file1.write('\n\n'.join(data))
file1.close()